module.exports = {
  apps: [
    {
      name: "session_sexy_1",
      script: "./servicePuppeteer/session.js",
      node_args: "--max-old-space-size=2048",
      interpreter_args: "-r dotenv/config",
      // instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 30,
      max_memory_restart: "2G",
      env_file: ".env",
      cron_restart: "0 2,4,8,11,16,21,23 * * *", // 02:00, 04:00, 08:00, 11:00, 16:00, 21:00, 23:00
      restart_delay: 5000,
    },
    {
      name: "session_sexy_2",
      script: "./servicePuppeteer/session2.js",
      node_args: "--max-old-space-size=2048",
      interpreter_args: "-r dotenv/config",
      // instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 30,
      max_memory_restart: "2G",
      env_file: ".env",
      cron_restart: "0 0,3,17 * * *", // Khởi động lại vào 0h (12h đêm), 3h sáng, 17h (5h chiều)
      restart_delay: 5000,
    },
    {
      name: "session_sexy_3",
      script: "./servicePuppeteer/session3.js",
      node_args: "--max-old-space-size=2048",
      interpreter_args: "-r dotenv/config",
      // instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 30,
      max_memory_restart: "2G",
      env_file: ".env",
      cron_restart: "30 16 * * *", // 4h30 chiều
      restart_delay: 5000,
    },
    {
      name: "session_sexy_4",
      script: "./servicePuppeteer/session4.js",
      node_args: "--max-old-space-size=2048",
      interpreter_args: "-r dotenv/config",
      autorestart: true,
      watch: false,
      max_restarts: 30,
      max_memory_restart: "2G",
      env_file: ".env",
      cron_restart: "30 17 * * *", // 5h30 chiều
      restart_delay: 5000,
    },
    {
      name: "server_sexy",
      script: "./server.js",
      node_args: "--max-old-space-size=2048",
      interpreter_args: "-r dotenv/config",
      // instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 30,
      max_memory_restart: "2G",
      env_file: ".env",
    },
  ],
};
